### ISSUE TITLE
Make PreNavbar Component Sticky

### ISSUE THREAD

**Issue by ParasY1724** [soham0005/ElectroKart#1]
**Description** : 
We need to modify the PreNavbar component to make it sticky, ensuring it remains visible at the top of the page as users scroll. This change will improve navigation and user experience across the site.

**Current Behavior**:
- PreNavbar scrolls out of view when the user scrolls down the page.

**Desired Behavior:**
- PreNavbar should remain fixed at the top of the viewport while scrolling.
- Other content should scroll underneath the PreNavbar.

Current Screenshot:
![ezgif-7-f65b748005](https://github.com/user-attachments/assets/173937c8-4b2a-47ba-aa37-7094eb6dba79)

Expected Screenshot : 
![ezgif-7-6cc89e145b](https://github.com/user-attachments/assets/5a1be3ca-14e1-47b5-a0fd-dac3db553555)

**Comment by ParasY1724** [comment]
Please Assign this task to me under gssoc-ext24

**Comment by soham0005** [comment]
@ParasY1724 let us know once you finish the task!

**Comment by ParasY1724** [comment]
@soham0005  i have create a PR please review it
