### ISSUE TITLE
Design Schema for Products

### ISSUE THREAD

**Issue by soham0005** [soham0005/ElectroKart#102]
For now, the data displayed on the frontend is being fetched through data.json file which is present in frontend/src/data folder

Objective:
- Design Schemas for Products such that, data can be stored in MongoDB
- Save those data into MongoDB

**Comment by SaanyaGarg5** [comment]
you can assign that task to me under gsssoc-ext and hacktoberfest.. level 3 label

**Comment by soham0005** [comment]
@SaanyaGarg5 Once the schema is designed, don't actually delete the data.json and dont change the frontend  for now, just design the schemas at the backend
Do reach out if you have any doubt

**Comment by SaanyaGarg5** [comment]
i have designed the schema ... pls check it..

**Comment by Akanshaku** [comment]
I would like to work on this issue pls assign me this @soham0005

**Comment by soham0005** [comment]
#155
