### ISSUE TITLE
Scroll to top button 

### ISSUE THREAD

**Issue by Devanshu1603** [soham0005/ElectroKart#106]
Adding a scroll to top button there must be a scroll to top button on the website . @soham0005  please assign this to me under gssoc-extended and with levels. will love to contribute.

**Comment by Akanshaku** [comment]
I would like to work on this issue pls assign me this @soham0005

**Comment by Devanshu1603** [comment]
@soham0005  please assign me this.

**Comment by vikas83pal** [comment]
@soham0005 please assign this to me under gssoc-extended and with levels.
