### ISSUE TITLE
Store Newsletter Email and Send Thank You Email

### ISSUE THREAD

**Issue by 17arindam** [soham0005/ElectroKart#108]
Feature Description
Implement functionality to store the email address of a user who subscribes to the newsletter in the database, and send a thank you email to the registered email address upon successful registration.

-Create an endpoint to accept the email address and store it in the database.
-After successful registration, trigger an email to the registered address.
-The email should thank the user for subscribing to the newsletter.

I will use nodemailer to send the mail to registered email

Use Case
this will increase user interaction and will help us to track the all the email that want to subscribe to the newsletter

**Comment by 17arindam** [comment]
@soham0005 please assign me this issue

**Comment by vikas83pal** [comment]
@soham0005 please assign this to me under gssoc-extended and with levels.

**Comment by soham0005** [comment]
@17arindam you can start working on it,
