### ISSUE TITLE
Dockerfile addition

### ISSUE THREAD

**Issue by haseebzaki-07** [soham0005/ElectroKart#112]
I want to add Dockerfile to the root of the application.

Adding the Dockerfile will encourage containerization of the application. The Dockerfile contaisn the codes that build image of the codebase and the same image can be run via docker to restrain from installing all the dependencies locally on our machines.

**Comment by soham0005** [comment]
Hello @haseebzaki-07, good idea, but this needs to be implemented once frontend and backend is fully functional.
Stay tuned

**Comment by haseebzaki-07** [comment]
Hi @soham0005 The project needs not to be finished for the Dockerfile addition . Docker automatically pulls the latest images of the project and can run in any environement be it LINUX/MAC/WINDOWS. So addition of dockerfile is never too early for a project as it smooths the development experience abstracting user from dependencies and resolving conflicts.

**Comment by soham0005** [comment]
@haseebzaki-07 great, you can start working on it then, do reach out if you have any doubts

**Comment by haseebzaki-07** [comment]
sure @soham0005
