### ISSUE TITLE
U.I. Enhancement 

### ISSUE THREAD

**Issue by aditya07389** [soham0005/ElectroKart#115]
hey @soham0005 I like your project and i want to contribute 

I was looking at the home page and i feel it will look good if i can add up a scroll reveal feature , which will make it visually appealing 

example site for scroll reveal feature .
https://www.nmit.ac.in/

you can assign this work to me !

please add the labels gssoc extd and hacktoberfest accepted

**Comment by Akanshaku** [comment]
I would like to work on this issue pls assign me this @soham0005
