### ISSUE TITLE
Add Github Greetings Bot

### ISSUE THREAD

**Issue by KiranBaliga** [soham0005/ElectroKart#12]
Hey 🥳 Looks like an amazing project idea! I see this repo lacks a small enhancement Github Greetings bot that sends auto messages to greet new users when they raise a PR or an issue. Let me know if you would like this level1 set up! Please assign to me if interested! (GSSoC24-Ext Contribution)

**Comment by soham0005** [comment]
@KiranBaliga you can start to work on this! <3

**Comment by soham0005** [comment]
@KiranBaliga any updates?

**Comment by KiranBaliga** [comment]
@soham0005 Please review the PR and action accordingly. Thank you. Please add level1 and gssoc24-ext to the PR. Thanks again.
