### ISSUE TITLE
Features: The Register and Login page is missing the footer

### ISSUE THREAD

**Issue by Lekkhasri** [soham0005/ElectroKart#120]
![image](https://github.com/user-attachments/assets/04c6f9f1-7ce6-4f8a-8167-e5f671ad57c6)
![image](https://github.com/user-attachments/assets/8f279eee-7de0-4701-b5ca-80b1f2af4aed)
I can add the footer to these two also can you assign the work to me @soham0005

**Comment by Akanshaku** [comment]
I would like to work on this issue pls assign me this @soham0005

**Comment by soham0005** [comment]
Login regsiter will not have footer as for now.
Happy Coding!
