### ISSUE TITLE
Cards in the Mobile View 

### ISSUE THREAD

**Issue by Bhanuprakash842** [soham0005/ElectroKart#121]
The cards width in the mobile view is very small as shown in the below screenshot.
![Screenshot 2024-10-09 225358](https://github.com/user-attachments/assets/00b96570-7e4e-4efb-ac62-58d25e797055)
I will increase the width of the cards in the mobile view.Please assign this issue to me under gssoc-ext,hacktoberfest-accepted labels.

**Comment by soham0005** [comment]
@Bhanuprakash842 Aslo adjust responsiveness for mobile version

**Comment by soham0005** [comment]
@Bhanuprakash842 any updates?
