### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by KiranBaliga** [soham0005/ElectroKart#13]
Hey 🥳! I see that repository is missing code of conduct. I would like to add a code of conduct developed from scratch for your project. Please let me know if it is okay to proceed. Please assign to me and add GSSoC24 Ext & level1 Labels.

**Comment by soham0005** [comment]
@KiranBaliga start working on the code of conduct and do attach the screenshot before making pull request

**Comment by KiranBaliga** [comment]
@soham0005 Please review the PR and action accordingly. Your feedback is highly appreciated. Thank you! 

(please add level1 and gssoc24-ext labels to the pull request)
