### ISSUE TITLE
[Feature]: Customer enquiry section

### ISSUE THREAD

**Issue by rahulvarma2005** [soham0005/ElectroKart#134]
I would like to add a section at the end of the home page where the customers will have an option to contact the customer support.

The space would have the option to fill email, problem, and description of the problem by the customer.
The issue is then directly forwarded to the customer-care gmail.

(this is different from the already existing option to fill gmail to be added to emailing list)

Note: I will also create a temporary gmail account for electrokart customer care. (I will share the credentials to you.)

**Comment by rahulvarma2005** [comment]
@soham0005 Could please assign this issue to me under the label of GSSoC-exd and Hacktoberfest.

**Comment by soham0005** [comment]
@rahulvarma2005 can you do frontend and backend for this?

**Comment by rahulvarma2005** [comment]
> @rahulvarma2005 can you do frontend and backend for this?

There is an online service that I would like to integrate for this feature. This would only require programming of the frontend.
Once this is done the form filled by customer is converted to email by that service and it would send an email to the customer service directly.

**Comment by soham0005** [comment]
@rahulvarma2005 good to go
