### ISSUE TITLE
Want to make footer more visually appealing like modern website

### ISSUE THREAD

**Issue by Suvadip-sana** [soham0005/ElectroKart#137]
For now the website footer is too simple compare to the other part of your website.
I want to make it more visually appealing like modern website.
Social media links are not in the footer. I also made like the same.
If you assign me this task i built it from scratch like this and also matching with your color combination -->

https://github.com/user-attachments/assets/508846f6-3c08-4e15-8523-6e12943ecb31

Please assign me this task. I want to improve this.
@soham0005

**Comment by Suvadip-sana** [comment]
@soham0005 ?

**Comment by soham0005** [comment]
@Suvadip-sana, this issue is already in progress
