### ISSUE TITLE
Wany to add a Rate Us functionality

### ISSUE THREAD

**Issue by Suvadip-sana** [soham0005/ElectroKart#138]
https://github.com/user-attachments/assets/9e0ee82d-76f4-4596-b21f-114374f359a1

I want to add a Rate Us functionality for this website which was attached on the footer.
I developed the same thing as you seen on video.

For now it only display a greetings as alert message.
Further you can add a backend functionality to display the ratings in webpage. Though it's an open source project, If i built this functionality, it would be great for you and other also for further improvement in this field.

Please assign me this ISSUE. I want to implement this feature.
@soham0005

**Comment by Suvadip-sana** [comment]
@soham0005

**Comment by soham0005** [comment]
@Suvadip-sana you can start working on it, make it look attractive and dont use contrast color

**Comment by Suvadip-sana** [comment]
@soham0005 
Sure!

**Comment by harshbhar0629** [comment]
Please @soham0005    Can i work on this issue because this issue is not assigned to anone..?
