### ISSUE TITLE
Add a New Register Page for Seamless User Sign-Up

### ISSUE THREAD

**Issue by yakhilgithub** [soham0005/ElectroKart#14]
Problem
The website does not have a Register Page, and users are unable to sign up.

Solution
I'll create the Register page. It will include fields like Full Name, Email, Password, and Confirm Password, along with validation for correct input and error messages for invalid entries. The page will be responsive and easy to use on all devices.

I want to work on this issue . Please assign it to me.

**Comment by PRathod27** [comment]
@yakhilgithub Sorry, another contributor is already working on this issue.
