### ISSUE TITLE
Improve Footer Design and Responsiveness

### ISSUE THREAD

**Issue by Prateekj2004** [soham0005/ElectroKart#142]
The footer of the Electrokart webpage currently lacks responsiveness and key features that can enhance the user experience.

Suggested Improvements:

Responsiveness: Ensure the footer adjusts properly on all devices (mobile, tablet, desktop).
Essential Links: Add important links such as Customer Support, About Us, Privacy Policy, and social media (Facebook, Instagram, Twitter, etc.).
Improved Layout: Use flexbox or CSS grid for better alignment and spacing of the footer elements.
Social Media Icons: Add social media icons with hover effects to make it more interactive.
Accessibility: Implement aria-labels for links and ensure keyboard navigation works smoothly.
Expected Outcome:

A refined footer design that aligns with Electrokart’s branding, improves user interaction, and enhances accessibility across all devices.

**I am happy to help contribute if needed. Let me know if any further details or designs are required.**

**Comment by soham0005** [comment]
@Prateekj2004 do share your footer ideas, as footer is to be designed newly.

**Comment by soham0005** [comment]
@Prateekj2004 have you started working?
