### ISSUE TITLE
Fix Login and Register Functionality & Add Google Authentication

### ISSUE THREAD

**Issue by rudrapratap63** [soham0005/ElectroKart#143]
**There are errors occurring in the login and registration processes that need to be fixed. Additionally, we want to improve user experience by implementing Google authentication using Firebase and enhancing the UI of both pages.**

**1. Fix Errors in Login and Registration:**
- Identify and resolve any existing issues that prevent users from successfully logging in or registering.
- Ensure that error messages are clear and informative to help users understand what went wrong.

**2.  Add Google Authentication:**
- Implement a "Continue with Google" button on both the login and registration pages using Firebase authentication.
- Ensure that the authentication process is seamless and secure.

**3. Enhance UI:**
- Redesign the login and registration pages to improve the overall user interface.
- Ensure the new design is visually appealing and aligns with the website's color scheme and style.

https://github.com/user-attachments/assets/30917024-672f-45dd-96df-99edd26c2eb3

**Comment by PRathod27** [comment]
@rudrapratap63 Another contributor is already working on this issue.
