### ISSUE TITLE
Add password validation to register page to improve personal data security

### ISSUE THREAD

**Issue by Hemant9808** [soham0005/ElectroKart#145]
I want to add password validation to check the strength of password 

- it contain 8 characters minimun,
- it contain atleast 1 uppercase letter
- it should contain atleast one special character
 
Confirm password field is missing in the register form , I will take care of whole validation of the registration and login process
Please assign me this issue and add gsoc-ext and hactober label to this issue 
@sanjay-kv @KiranBaliga @soham0005

**Comment by soham0005** [comment]
@Hemant9808, do attach the screenshot once you are done

**Comment by Hemant9808** [comment]
> @Hemant9808, do attach the screenshot once you are done

Alright @soham0005
