### ISSUE TITLE
I want to profile page , where user can see and update their personal information

### ISSUE THREAD

**Issue by Hemant9808** [soham0005/ElectroKart#146]
Profile page is missing in this website 
I will add the profile page , where user can see their email and other details, i will make the whole page which will be perfectly optimised and good looking and will match with the current theme of the website .
 

Kindly assign me this issue so that i can start work on this as soon as possible.
@soham0005 @sanjay-kv @KiranBaliga  @sakshii00

**Comment by soham0005** [comment]
Hello @Hemant9808, this feature is already implemented. Thank you for your concern
Happy Coding!
