### ISSUE TITLE
Transform the home page with a Modern, interactive Carousel

### ISSUE THREAD

**Issue by yakhilgithub** [soham0005/ElectroKart#15]
Problem:
The current home page features a basic carousel that appears simple and lacks engagement which may lead to a diminished user experience.

Solution:
I will update the carousel to make it modern and interactive. This will include adding smooth animations and transitions to grab users' attention and make it visually appealing. The new design will be responsive, so it looks great on all devices. I will also include easy to uuse controls like next/previous buttons and pagination dots for better navigation. By featuring dynamic content that highlights important items or promotions, we can make the carousel even more attractive. Overall, these changes will improve user engagement and enhance the home page's look.

Please assign it to me.

**Comment by PRathod27** [comment]
Hello @yakhilgithub, you start working on it.

**Comment by yakhilgithub** [comment]
@PRathod27 I am working on this

**Comment by PRathod27** [comment]
@yakhilgithub What's the status of the project?

**Comment by PRathod27** [comment]
@yakhilgithub You have been working on this issue for more than 3 days and not even providing any response.
This is message to convey that if you won't provide any updates then you will un-assigned.

**Comment by divi-24** [comment]
Please assign me(@divi-24) for the improvisation @PRathod27

**Comment by soham0005** [comment]
@divi-24 you can start working on this

**Comment by soham0005** [comment]
@divi-24 any updates?

**Comment by divi-24** [comment]
> @divi-24 any updates?
> 

Almost done sir i'll update the @PRathod27 soon

**Comment by divi-24** [comment]
@soham0005 @PRathod27 @yakhilgithub 

https://github.com/user-attachments/assets/d3d7579c-538c-4345-89db-443aa314f290


https://github.com/user-attachments/assets/2558213d-5384-403b-9ea7-2c41c4f73d0a

these are my suggestions which we can do to make carousel interactive and modern as per the our website electrokart , i  can do add more creative and animation if suggested, suggest me if we need anything more or anything which i have missed to do and if these carousels are accepted please let me know so can work on the changes i have to make in the main code file

**Comment by PayalKumari10** [comment]
> @soham0005 @PRathod27 @yakhilgithub
> 
>  WhatsApp.Video.2024-10-11.at.12.35.51.mp4 
>  WhatsApp.Video.2024-10-11.at.12.35.54.mp4 
> these are my suggestions which we can do to make carousel interactive and modern as per the our website electrokart , i can do add more creative and animation if suggested, suggest me if we need anything more or anything which i have missed to do and if these carousels are accepted please let me know so can work on the changes i have to make in the main code file

Hello @divi-24 , Reviewing this with our team—please wait. We'll merge it once everything looks good!

**Comment by PayalKumari10** [comment]
@divi-24  please apply your design 2; it's awesome.

**Comment by soham0005** [comment]
@divi-24 any updates?

**Comment by divi-24** [comment]
> @divi-24 any updates?
> 

Yup having some issues in the , probably gonna get it done on Thursday

**Comment by divi-24** [comment]
#252
