### ISSUE TITLE
Adding LogIn via OTP

### ISSUE THREAD

**Issue by Abhigaba** [soham0005/ElectroKart#151]
To enhance the user login experience, I can create a login using otp system making the website more intuitive.

**Comment by AdibaNaushad** [comment]
and i can do documentation work

**Comment by soham0005** [comment]
@Abhigaba just elaborate more on how you are goinh to implement and which libraries/ packages you are going to use

**Comment by Abhigaba** [comment]
There are two ways : 
1. Via SMS, it can implemented by using firebase or a third party service like twilio. (Firebase will be free but not twillio)
2. Via Email, using nodemailer library in  the backend to send the email and verifying the otp. 

@soham0005 , depending on the requirements it can be imlpemented in both ways.

**Comment by soham0005** [comment]
@Abhigaba you can start working on it, you can use any of the method which is free of cost

**Comment by soham0005** [comment]
@AdibaNaushad, raise another issue for the documentation you mentioned, i'll assign it to you

**Comment by soham0005** [comment]
@Abhigaba any updates?

**Comment by Abhigaba** [comment]
@soham0005  , yes I have created the backend part and will be opening the pr  for it in a minute.  It is successfully running and testted on postman.  

Before merging  add  these things in the .env file 
1.  OAUTH_CLIENTID, 
2.  OAUTH_CLIENT_SECRET, 
3.  OAUTH_REFRESH_TOKEN

**Comment by Abhigaba** [comment]
Will do the frontend part tomorrow.
