### ISSUE TITLE
Register Button Status changed to Logout when User is Logged in 

### ISSUE THREAD

**Issue by Vishesh-Tripathi** [soham0005/ElectroKart#153]
I  want to add a feature or logic by which Register button status changed to Logout button when user is logged in .

**Comment by soham0005** [comment]
@Vishesh-Tripathi you can start working on it.
Also implement the following:-

- when not logged in, hide the profile icon on navbar
- when logged in, show the profile icon on navbar

**Comment by Vishesh-Tripathi** [comment]
sure
