### ISSUE TITLE
Product Design Schema structure

### ISSUE THREAD

**Issue by soham0005** [soham0005/ElectroKart#156]
Objectives:

- Remove the redundant code in index.js and model/schema.js
- Ensure the schema designed in schema.js is correct for the data present in frontend/src/data/data.json

**Comment by GLITCH-in-MATRIX9** [comment]
I would be happy to work upon this issue. Please assign this to me.

**Comment by soham0005** [comment]
@GLITCH-in-MATRIX9 you can start working on it.
Do reach out if you have any doubts
