### ISSUE TITLE
The navbar has some design issues

### ISSUE THREAD

**Issue by GLITCH-in-MATRIX9** [soham0005/ElectroKart#159]
Hi ! 
I'd love to contribute to improving the design of the Navbar as well as adding in a few more of my ideas to it.
I've worked on something related to this and I believe it can be improved to something like this!.

![Screenshot 2024-10-13 015101](https://github.com/user-attachments/assets/183f5ccc-83f9-4c42-af7b-bd439b7960c7)

**Comment by soham0005** [comment]
Hello @GLITCH-in-MATRIX9 , we do not require search bar in Nav anymore, so if you have any other idea for Nav feel free to connect
