### ISSUE TITLE
The website does not have a Register Page, and users are unable to sign up.

### ISSUE THREAD

**Issue by GitWizzz** [soham0005/ElectroKart#16]
I will develop a responsive Register Page that will include the following features:

Input Fields: Full Name, Email, Password, and Confirm Password
Form Validation: Real-time frontend validation for proper input (email format, matching passwords, etc.)
Error Handling: Clear error messages for invalid entries like mismatched passwords or incorrect email format
Design: A clean, user-friendly design that adapts well to both desktop and mobile devices

**Comment by PRathod27** [comment]
@GitWizzz Sorry, but another contributor already working on this issue.
