### ISSUE TITLE
Feature: Adding OTP Based Forget Password (Frontend + Backend)

### ISSUE THREAD

**Issue by Sourabh782** [soham0005/ElectroKart#160]
If users forget theri password, currently they dont have any way of regaining access to their account

![Screenshot 2024-10-13 081226](https://github.com/user-attachments/assets/c71e9bd7-40d3-45a6-a420-1a7cf225c8d2)

Idea: I suggest adding a forget password route, so users can reset their password

work flow:
1. user enter their email id on forget password page,
2. backend generates an OTP which is stored on DB linked with the email
3. a mail is sent on email entered by user
4. uset enters the OTP on verify OTP page
5. backend compares user's otp with otp in backend, if valid user is redirected to reset password page
6. the password is reset with new password

**Comment by SaanyaGarg5** [comment]
you can assign this task to me..

**Comment by Sourabh782** [comment]
> you can assign this task to me..

Hey @SaanyaGarg5, I created the issue, so I'll get chance to work on it
