### ISSUE TITLE
Wishlist feature

### ISSUE THREAD

**Issue by Veda273** [soham0005/ElectroKart#164]
I would like to add the wishlist feature, and create a wishlist page.
 @soham0005 , can you assign me this issue under gssoc-extend, I would like to work on it.

**Comment by soham0005** [comment]
Please elaborate what things you will be adding in this issue

**Comment by Veda273** [comment]
@soham0005 i would like to include add these features:

1)Wishlist Icon: Add a small heart beside each product. When clicked, this will add the item to the user's wishlist.

2)Wishlist Page: Create a wishlist page where users can view all the items they have added to their wishlist. Using Context API to track the wishlist across all pages. This will avoid duplicating logic for each page and ensure the wishlist is accessible from anywhere.

3)Header Wishlist Icon: Include a wishlist icon in the website's header, allowing users to quickly navigate to their wishlist page.

**Comment by soham0005** [comment]
@Veda273 you can start working on it. Do reach out if you have any doubts

**Comment by soham0005** [comment]
@Veda273 any updates?
