### ISSUE TITLE
UPDATION IN README FILE REQUIRED

### ISSUE THREAD

**Issue by soham0028** [soham0005/ElectroKart#168]
Hello @soham0005 
the current readme file lacks proper structure and does not contain :
1. featured in section 
2. contributors  section 
3. forkers and stargazers section 
4. back to top button 

Kindly assign me the issue under hacktoberfest and gssoc-extd labels so my work counts under these events as i am a contributor for these events

**Comment by soham0005** [comment]
You can start working on it

**Comment by soham0028** [comment]
okay thankyou will revert back asap
