### ISSUE TITLE
Bug: The search button covers the register button

### ISSUE THREAD

**Issue by GLITCH-in-MATRIX9** [soham0005/ElectroKart#171]
![image](https://github.com/user-attachments/assets/2ce7e20e-750f-470f-b922-1f67ea20db77)

The search button overlaps with or covers the register button on the page, making it difficult or impossible for users to click the register button. This issue affects the overall user experience by preventing users from completing the registration process and navigating the page smoothly.

Please assign me this issue. would be happy to contribute.

**Comment by soham0005** [comment]
Remove the Search bar component

**Comment by GLITCH-in-MATRIX9** [comment]
sure I'll do that

**Comment by GLITCH-in-MATRIX9** [comment]
Thank you for taking this into consideration
Confirming again...the button has to removed right ? not redesigned ?

**Comment by soham0005** [comment]
Yess, remove the search button component
