### ISSUE TITLE
🚀 [UI Enhancement ] -Adding Gsap Animations to landing page for better UI experinece | gssoc-ext | level 3

### ISSUE THREAD

**Issue by Hamza1821** [soham0005/ElectroKart#185]
### *i will first integrate GSAP to react then create UseEffect for rendering animation when page is loaded , inside useEffect i will create a gsap context that make sure that animations are played only when the component is already rendered than i will use gsap fromTo mehode use create the desire animations, also i will be using GSAP timeline for even better and time sync animations*

please asign this to me under  gssoc-ext level 3

**Comment by soham0005** [comment]
Hello @Hamza1821, right now this feature is not needed as the Animation is implemented and will be merged into hosted project in upcoming days.
Happy Coding!
