### ISSUE TITLE
Severe changes required in backend.

### ISSUE THREAD

**Issue by PRathod27** [soham0005/ElectroKart#190]
1. The routes for register are called twice instead of using it in the index.js file.
2. Schema has been defined in the index.js file, besides it should contain different files.
3. A better structure is required.

@soham0005 @PayalKumari10 Do have a look at the backend.
Assign me this task so I can make the code cleaner and simple to understand.

**Comment by GLITCH-in-MATRIX9** [comment]
Yes I noticed these too!
