### ISSUE TITLE
Language switch not translating all texts in some languages

### ISSUE THREAD

**Issue by 18Prachi** [soham0005/ElectroKart#192]
*Issue:*
The language switch feature does not translate all the content across different languages, resulting in some text remaining untranslated.
FAQs are available only in English.

*Expected Behavior:* 
All texts should be translated accurately based on the selected language.

*Screenshot:*
![Screenshot (302)](https://github.com/user-attachments/assets/bebc3c40-17f6-4875-b4c1-3990e8f12b79)
![Screenshot (303)](https://github.com/user-attachments/assets/c82533f7-d4ee-4678-b834-f323fc274f68)

GSSoC Contributor: Could you please assign this issue to me under GSSoC'24 extended?

**Comment by soham0005** [comment]
@18Prachi please elaborate how will you fix this
