### ISSUE TITLE
Improper alignment of pictures in the "Featured" section

### ISSUE THREAD

**Issue by 18Prachi** [soham0005/ElectroKart#193]
*Issue:*
The pictures in the "Featured" section are not properly aligned, with no spacing between images and excessive space around them, resulting in an unbalanced layout.

*Expected Behavior:* 
The images should be properly aligned with consistent spacing between them and minimal space around the outer edges.

*Screenshot:*
![Screenshot (304)](https://github.com/user-attachments/assets/d9192116-8d87-4109-9ada-bbb9a486e202)

GSSoC Contributor: Could you please assign this issue to me under GSSoC'24 extended?

**Comment by soham0005** [comment]
@18Prachi You can start working on it, feel free to reach out if you have any doubts
