### ISSUE TITLE
Add forgot password button on login page and new page for forgot password in UI

### ISSUE THREAD

**Issue by AkankshaSinghK** [soham0005/ElectroKart#197]
@soham0005 

On login page there is no button for forgot password and on clicking on forgot password new page should come on Ui to reset the password.

Kindly assign this issue to me and add gssoc-extd and hactoberfest tags and level it.

**Comment by divi-24** [comment]
Please assign me for this, as i have also done this adding sign in option in registration page and making ui better and i can easily add this option too @PRathod27 @PayalKumari10 @soham0005

**Comment by soham0005** [comment]
@AkankshaSinghK any updates?

**Comment by divi-24** [comment]
here is the preview of above issue solution @soham0005 @PRathod27 @PayalKumari10 

Uploading WhatsApp Video 2024-10-15 at 23.23.01.mp4…
