### ISSUE TITLE
Feature: Login and Signup Frontend

### ISSUE THREAD

**Issue by Vishesh-Tripathi** [soham0005/ElectroKart#2]
Two Separate Components: Login and Signup

Fields to be included in Signup:
- Name
- Password
- Email ( unique)
- Phone number

Fields to be included in Login:
- Email
- Password

- Validations required such as No empty value, unique email, etc
- Form should be responsive

**Comment by soham0005** [comment]
@Vishesh-Tripathi do start the task, don't forget to create new branch while doing your work and attach screenshot while creating PR

**Comment by Vishesh-Tripathi** [comment]
Sure I will .
But I have a question I think there is no api for backend so I should use a dummy api

**Comment by soham0005** [comment]
@Vishesh-Tripathi For now, have one dummy get api

**Comment by soham0005** [comment]
@Vishesh-Tripathi Any updates?

**Comment by ak3264114** [comment]
@Vishesh-Tripathi can i work on this issue

**Comment by Vishesh-Tripathi** [comment]
> @Vishesh-Tripathi Any updates?

I am working on it it tomorrow I will make a PR

**Comment by soham0005** [comment]
@Vishesh-Tripathi do reach out to us if you feel stuck or having any doubts <3

**Comment by Vishesh-Tripathi** [comment]
@soham0005 there is routing Problem(my component is rendering but not showing i tried to change routing then it will working fine) can you please explain how are you rendering these things .  if you allow me then i can make layout and then render but this willl change your routing . 
here is screenshot 
![Screenshot 2024-10-04 095907](https://github.com/user-attachments/assets/253c0c36-a1f0-449a-9bc8-105eedd0a132)

**Comment by PRathod27** [comment]
@Vishesh-Tripathi Connect with me on LinkedIn. I'll explain you. 
https://www.linkedin.com/in/prem-arun-rathod
