### ISSUE TITLE
Improvement in the Ui of registration Page

### ISSUE THREAD

**Issue by GLITCH-in-MATRIX9** [soham0005/ElectroKart#200]
The sign in page looks really dull.
The UI can be improved along with more sign-in features such as google sign-in for better user experience 
![image](https://github.com/user-attachments/assets/70bba048-8ecd-46e0-8423-3a5b9dca53c1)

please assign me this issue.

**Comment by soham0005** [comment]
@GLITCH-in-MATRIX9, do share the screenshot of the designs

**Comment by shrutilad20** [comment]
The sign in page looks really dull.
The UI can be improved along with more sign-in features such as google sign-in for better user experience
image

please assign me this issue.

**Comment by divi-24** [comment]
Dear [@soham0005 @PRathod27 @PayalKumari10 ],

 I would like to request to be assigned the task of creating the registration page for electrokart project. The registration page would resemble the one attached below, including fields for the user's name, email, and password, as well as the option to sign in using Google or LinkedIn.

This feature is essential for enhancing user experience and simplifying the registration process. I'm excited to work on this and believe it will be a valuable addition to the project.

Thank you for considering my request. I look forward to your feedback and assignment details.
