### ISSUE TITLE
Signup and Login Routes Not Working 

### ISSUE THREAD

**Issue by bhardwaj-hrishabh** [soham0005/ElectroKart#205]
I found an issue  related to the user signup and login functionalities. When I try to register a user or log in, the routes are not working as expected. After filling in the details and clicking the "Register" or "Login" button, nothing happens.

**Expected Behavior:**
After clicking "Register" or "Login," the user should be redirected to the appropriate page, and a new user should be created (for register) or logged in (for login).

**Actual Behavior:**
- Nothing happens after clicking the "Register" or "Login" button.
- The console log shows an error:
           `POST https://electro-kart-frontend.vercel.app/undefined/api/v1/auth/register 405 (Method Not Allowed)`

**Potential Cause:**
The error message suggests that the route is not being correctly defined, as it seems to be pointing to an "undefined" URL. This could be due to a misconfiguration in the API URL or missing endpoint in the backend.

**Possible Solution:** 
 I believe this issue could be resolved by:
- Checking the API URL and ensuring it is correctly set for both signup and login routes.
- Updating the Signup.jsx file to handle the API call properly.
- Ensuring that the backend is correctly handling the routes and that the proper method (POST) is being allowed.

I would be happy to take this up as part of my contribution to GirlScript Summer of Code and Hacktoberfest. Let me know if I can work on fixing this!

**Comment by soham0005** [comment]
Backend is yet to be deployed, once it is deployed it will work.
Happy Coding!
