### ISSUE TITLE
Error on Subscribing via Email

### ISSUE THREAD

**Issue by RohanSai22** [soham0005/ElectroKart#207]
@soham0005 

When I enter my email address and click on the Subscribe button, an error message is shown: "error occurred." The subscription process doesn’t go through, and the error seems to persist regardless of the email entered.

Screenshots
![Screenshot 2024-10-15 134851](https://github.com/user-attachments/assets/7017dd94-2280-4409-9876-496199b2665d)

This issue occurs across different browsers. I have tried using valid email formats, but the same error persists.

Checklist
 I have checked the existing issues
 I have read the Contributing Guidelines
 I'm a GSSoC'24-Extd contributor
 I'm a Hacktoberfest'24 contributor
 I am willing to work on this issue

**Comment by KiranBaliga** [comment]
@RohanSai22 I am not project owner not maintainer. Sorry!

**Comment by RohanSai22** [comment]
> @RohanSai22 I am not project owner not maintainer. Sorry!

My Bad ! Sorry for the inconvenience

**Comment by soham0005** [comment]
Backend is yet to be deployed, once it is done it will work
Happy Coding!
