### ISSUE TITLE
Improve Scroll Bar ,social media icons and Preloader 

### ISSUE THREAD

**Issue by VidhanThakur09** [soham0005/ElectroKart#208]
### Description

The current Scroll bar Ui has a very basic layout and outdated design and site Loading has no preloader and the social media Icons have very basic styling and hover effect. The screen becomes blank when the website loads. Enhancing the colour scheme of Thumb and Track, improving the preloader and modernizing the social media icons design would greatly improve the user experience and website presentation

**Describe the solution**

- Redesign the Scroll bar, social media icons and preloader for better visual appeal.
- Improving the scroll bar thump and track.
- Improving the preloader.

**Without Preloader , with no enhancement in social media icons and without improvement in Scroll BAR**

https://github.com/user-attachments/assets/602e5cd6-dbaa-4933-b33f-6adabf10f9a7

**Preloader Mockup**

https://github.com/user-attachments/assets/581ba556-6358-4767-88ee-db82b2b33997

**Social media mockup**

https://github.com/user-attachments/assets/4d8d0544-739d-4bc5-a306-8b2209054c8d

**Additional context**
@soham0005  can you assign this issue to me with labels "gssoc-ext" with levels ,"hacktoberfest-accepted";

**Comment by soham0005** [comment]
Do reach out if you have any doubts

**Comment by VidhanThakur09** [comment]
Thank you for assigning this to me, I will definitely reach out if any doubt arise.
