### ISSUE TITLE
Backend setup

### ISSUE THREAD

**Issue by soham0005** [soham0005/ElectroKart#21]
- Node, Express and MongoDB setup for the project
- MVC based architecture setup
- Do attach the screenshot of sample API

**Comment by shubham18102000** [comment]
I would like to take on this task to set up the Node.js, Express, and MongoDB backend following the MVC architecture. I have experience working with these technologies and am confident that I can deliver a well-structured and scalable solution. I will follow the outlined steps, ensure proper code organization, and test the API endpoints.

Please assign me this task, and I'll get started right away!

Thanks,
Shubham Chamoli

**Comment by samriddhitiwary** [comment]
@soham0005 could please assign this to me under the Hactoberfest label also

**Comment by soham0005** [comment]
@shubham18102000 you can start working on this

**Comment by shubham18102000** [comment]
@soham0005  thankyou

**Comment by soham0005** [comment]
@shubham18102000 feel free to reach out for doubt, don't forget to star the repo <3

**Comment by soham0005** [comment]
@shubham18102000 any updates?

**Comment by shubham18102000** [comment]
@soham0005 working on register and signup page

**Comment by PRathod27** [comment]
@shubham18102000  Any updates?

**Comment by shubham18102000** [comment]
@PRathod27 created login page and register page

**Comment by shubham18102000** [comment]
@PRathod27  are you working on backend part '

**Comment by PRathod27** [comment]
> @PRathod27  are you working on backend part '

No, I'm not working on it.

**Comment by shubham18102000** [comment]
@soham0005 

![Screenshot 2024-10-04 105448](https://github.com/user-attachments/assets/70f882da-3a8b-4939-a0b7-006d398efa29)
![Screenshot 2024-10-04 105457](https://github.com/user-attachments/assets/9ddcd24a-a148-4523-9742-8e18901a3485)

**Comment by shubham18102000** [comment]
@soham0005   after login  page , we show the product items page  and having a cart option so person can buy that product

**Comment by soham0005** [comment]
@shubham18102000 great work! just one enhancement, please do hash the password and then save it into database

**Comment by soham0005** [comment]
@shubham18102000 if the initial setup of backend is done, do make the PR so that the rest backend work can be merged

**Comment by shubham18102000** [comment]
@soham0005  pr is done
