### ISSUE TITLE
improve the UI  of card view

### ISSUE THREAD

**Issue by dipeshkumar799** [soham0005/ElectroKart#210]
i my opinion , in home page there is 3 cards. in this  3 card i want to give gap  between the cards  and while hover this card  doesn't look good while hovering. also i fixed it 
![issue 1](https://github.com/user-attachments/assets/40cf748e-f3a5-4965-aa10-fdbba19816aa) 

@soham0005 please assign this issue to me. i can work on that

**Comment by soham0005** [comment]
It is already fixed and will get reflected once the PR is merged.
happy Coding!
