### ISSUE TITLE
Create a Responsive Navbar Section.

### ISSUE THREAD

**Issue by PayalKumari10** [soham0005/ElectroKart#23]
![navbar electron11](https://github.com/user-attachments/assets/2c84d36a-b952-41dd-9bd0-1f89542edc6b)
### Description
Implement a responsive navbar section similar to the example provided, which includes:
1. **Logo Section**: A clickable logo on the left side.
2. **Menu Items**: Horizontal navigation links such as "Store", "Phones", "Tablets", "TV & Smart Home", "Smart Watch & Audio", "Discover", and "Support".
3. **Icons**: Right-aligned action icons for search, cart, and profile.

### Objectives
- Build a reusable and responsive navbar using React.js for the frontend.
- Ensure the navbar adapts for different screen sizes (desktop, tablet, and mobile).
- Use React Icons or custom SVGs for the action icons.
- Make the design visually consistent across all pages of the application.
- Backend integration using Express.js and Node.js if necessary for any dynamic data.

### Requirements
1. Add a **logo** on the left side that links to the homepage.
2. Create **navigation links** for the following items: Store, Phones, Tablets, TV & Smart Home, Smart Watch & Audio, Discover, Support.
3. Include **action icons** on the right side for:
   - Search
   - Shopping Cart
   - User Profile
4. Ensure the navbar is **responsive** and adjusts well on smaller screens. For mobile view, the menu should become a **hamburger menu**.
5. Use **Tailwind CSS** for the styling and **React.js** for the component structure.
6. If dynamic data is required, use **Express.js** and **Node.js** to handle backend API calls, and **MongoDB** if any data storage is necessary.

### Tech Stack
- **React.js** for building the component (Frontend).
- **Tailwind CSS** for styling and responsiveness (Frontend).
- **Node.js** with **Express.js** for any server-side logic (Backend).
- **MongoDB** for any data storage (Backend, if required).
- **React Icons** or **SVGs** for action icons.

### Acceptance Criteria
- The navbar should display correctly with a **logo, navigation items**, and **icons**.
- The design should be responsive across different screen sizes (desktop, tablet, and mobile).
- Navigation items should be clickable and point to corresponding sections of the site.
- Action icons should have hover effects.
- The navbar must be consistent with the overall UI of the site.
- Ensure smooth integration between the frontend (React) and backend (Node.js, Express.js).

**Comment by Abhigaba** [comment]
Can you assign me this issue ? , I can meet your requirements for a responsive navbar, which will be able to meet your requirements.

**Comment by PayalKumari10** [comment]
> Can you assign me this issue ? , I can meet your requirements for a responsive navbar, which will be able to meet your requirements. @PayalKumari10

@Abhigaba , Thanks for offering to take this on! Before I assign the issue, could you briefly outline how you plan to approach building the responsive navbar? This will help ensure everything aligns with the project requirements.

**Comment by Abhigaba** [comment]
I plan to use TailWindCSS to ensure the design is responsive and using two different flexbox containers for left and right navbar components, Using react-router alongside can ensure the url dynamics changes. Navbar can be used as Layout with react-router instead of importing it into other routes.  Rest is just designing with JSX and tailwind.

@PayalKumari10

**Comment by PayalKumari10** [comment]
> I plan to use TailWindCSS to ensure the design is responsive and using two different flexbox containers for left and right navbar components, Using react-router alongside can ensure the url dynamics changes. Navbar can be used as Layout with react-router instead of importing it into other routes. Rest is just designing with JSX and tailwind.
> 
> @PayalKumari10

okay @Abhigaba

**Comment by Abhigaba** [comment]
Created a reusable and  responsive  navbar without tailwind. If tailwind is configured it could disrupt the whole  styling for the webapp.  Check it once and inform me the changes that needed to be required. I am currently working on creating a  expanding searchbar. 

@PayalKumari10 
![Screenshot from 2024-10-04 14-59-07](https://github.com/user-attachments/assets/013b3044-09f1-4432-8ac5-adbc3f422b86)

![Screenshot from 2024-10-04 14-59-22](https://github.com/user-attachments/assets/c324092b-a3b7-476e-95e9-1bf55a21d231)

**Comment by soham0005** [comment]
@Abhigaba great work!. please do change the logo and for now keep it something else and proceed for the PR

**Comment by soham0005** [comment]
@Abhigaba please do revert the logo back, and also in the navbar replace Discover with Register, and add Route to register component
There is an existing routing to Register component
![image](https://github.com/user-attachments/assets/612b9335-2768-483a-b1c4-86ea5ed6c349)

**Comment by soham0005** [comment]
@Abhigaba connect on discord once you are free

**Comment by Abhigaba** [comment]
Sure, can you provide me with the discord invite link.

**Comment by soham0005** [comment]
@Abhigaba  soham.215 is my discord username
