### ISSUE TITLE
Adding footer in FAQs page

### ISSUE THREAD

**Issue by nksmanya** [soham0005/ElectroKart#238]
I think it will be better if we add the footer section in the FAQs page too
Please do assign this issue to me. @soham0005

**Comment by soham0005** [comment]
@nksmanya you can work on it, do reach out if you have any doubts
Happy Coding!

**Comment by sayiamarora** [comment]
hey @soham0005 could you assign me this issue as i see its not attempted.

**Comment by PRathod27** [comment]
@nksmanya Any updates?

**Comment by nksmanya** [comment]
I am working on it. 
I will soon let you know.

**Comment by nksmanya** [comment]
I have a trouble in opening the FAQs page...
The page is not opening for me. It is just keep on loading.
I have been trying for 3 to 4 days!

**Comment by soham0005** [comment]
@nksmanya the bug is solved, you can add footer
