### ISSUE TITLE
Active tab in accessories section and fixing alignment of featured section

### ISSUE THREAD

**Issue by sakshii00** [soham0005/ElectroKart#25]
The alignment of featured is not proper, it can be seen in the screenshot below-

![image](https://github.com/user-attachments/assets/7ea507e6-5322-4c94-94c1-1de34e46c502)

and i would like to add active element for the tab that is open in accessories 
![image](https://github.com/user-attachments/assets/5a1e55f1-bb93-48e7-9715-e7c4cdc97375)
![image](https://github.com/user-attachments/assets/a9fd7295-37c6-4d34-8b72-85b9dbd4c469)
Like in above, music is open so the line that comes on hover would stay there is music is open and vice and versa for other tabs too.

**Comment by PRathod27** [comment]
@sakshii00 You can start working on it.

**Comment by sakshii00** [comment]
okay

**Comment by PRathod27** [comment]
@sakshii00  Any updates?

**Comment by sakshii00** [comment]
Hello, I will start working on it today. Sorry I have exams going on.. I will complete this over weekend, don't worry

**Comment by PRathod27** [comment]
> Hello, I will start working on it today. Sorry I have exams going on.. I will complete this over weekend, don't worry

Ok. Try to complete it before Monday.

**Comment by PRathod27** [comment]
@sakshii00 First pull the current changes of the projects and as there are some changes in the files structure, please make according to it.

**Comment by sakshii00** [comment]
This preview is from vercel and vercel displays master branch only (most recent updated)~ So this change is existing on master branch but just in case I will check on local but I am sure it would be same as vercel. @PRathod27

**Comment by PRathod27** [comment]
@sakshii00 as there are changes in the routings, you will have to make changes. Do pull it. You will understand.

**Comment by sakshii00** [comment]
@PRathod27 I saw the changes on local. It is same as vercel, my issue states adding active present thing on the accessories tab but now that it is a different page entirely, I don't know what to change to it anymore. Can you please guide me on how the changes should be implemented? Should I make the routing same as previous and then make the changes I proposed because I can't make the changes I proposed on this one.

**Comment by PRathod27** [comment]
> @PRathod27 I saw the changes on local. It is same as vercel, my issue states adding active present thing on the accessories tab but now that it is a different page entirely, I don't know what to change to it anymore. Can you please guide me on how the changes should be implemented? Should I make the routing same as previous and then make the changes I proposed because I can't make the changes I proposed on this one.

I will surely guide you. Tomorrow I'll get back to you.

**Comment by sakshii00** [comment]
Yes sure!

**Comment by PRathod27** [comment]
> Yes sure!

Do connect with me on LinkedIn:
https://www.linkedin.com/in/prem-arun-rathod

**Comment by PRathod27** [comment]
@sakshii00 Have you fixed the issue? Let us help you out on your queries.

**Comment by sakshii00** [comment]
I sent you a connection request on linkedin. Yet again, there is nothing to fix now since the routing has been changed so i guess the issue can be closed unless you have something you would like to implement in relevance to the changes I proposed. @PRathod27

**Comment by PRathod27** [comment]
I have already accepted your connect request. Today, we shall have a meet and let's fix this issue. 
I don't want you to go with empty hands.
Do convey me when you can have a meet?

**Comment by sakshii00** [comment]
I am working on it @Akanshaku
