### ISSUE TITLE
Bug: Infinite Loading on FAQs Page

### ISSUE THREAD

**Issue by soham0005** [soham0005/ElectroKart#270]
There's a bug in FAQs component, the loader is being displayed infinitely.
Problem to be solved:
1) Modfiy code such that loader is shown only when page content is rendering
2) stop loader once rendered

**Comment by RNAdvani** [comment]
@soham0005  i would like to work on this can you assign this to me

**Comment by PRathod27** [comment]
@RNAdvani Any updates?

**Comment by RNAdvani** [comment]
yes i would push it by night,

**Comment by RNAdvani** [comment]
fixed in #281

**Comment by RNAdvani** [comment]
@soham0005 @PRathod27 kindly check
