### ISSUE TITLE
ContactUs Backend functionality using nodemailer

### ISSUE THREAD

**Issue by harshbhar0629** [soham0005/ElectroKart#271]
When user wants to connect with you via mail then website not support contact us functionality:)

I want to implement a contact Us functionality using nodemailer.

@soham0005 Please assign this issue to me:)

**Comment by PRathod27** [comment]
@harshbhar0629 You can start working on this project.
Try to do this within 2-3 days.
Happy Coding!

**Comment by harshbhar0629** [comment]
Ok i will:)
