### ISSUE TITLE
Exclusive Offers

### ISSUE THREAD

**Issue by PayalKumari10** [soham0005/ElectroKart#274]
Create an **Exclusive Offers** section to showcase product bundles, top-selling items, and festive discounts for **Diwali/Festival**. This section will feature a carousel with multiple product images and a promotional video embedded to highlight key deals.

**Objectives:**

- Build a reusable and responsive carousel for exclusive Diwali offers.
- Include promotional banners, product categories, and deals to attract customers.
- Embed a promotional video to highlight top festive offers.
- Ensure the section aligns with the overall UI/UX design of the site.

**Offer Highlights:**

1. Smart Bundles: "Unlock extra savings with product bundles – Save up to 45%!"
2. Bestselling Smartphones: "Get the most popular smartphones at exclusive **Diwali/Festival** discounts!"
3. Smart TV: "Enjoy crystal-clear displays with deals on the latest Smart TVs."
4. Power Banks: "Power on the go! Shop high-capacity power banks with fast charging."
5. Audio Products: "Experience immersive sound with wireless earbuds, headphones, and speakers."

**Sub-Tasks:**

1.  Add a carousel section with product images and offers.
2.  Upload Diwali/Festival banners for product promotions.
3.  Embed and test the promotional video to ensure smooth playback.
4.  Implement hover effects for each product card in the carousel.
5.  Test responsiveness across different devices (desktop, tablet, mobile).

**Tech Stack:**

1. Frontend: React.js, Tailwind CSS
2. Icons: React Icons / Custom SVGs

**Acceptance Criteria:**

1. The carousel should display correctly across all devices.
2. Product offers and banners must align with the Diwali/Festival campaign theme.
3. The carousel should have smooth navigation with no lags or glitches.
4. Each product card should have appropriate hover effects to enhance interactivity.

https://github.com/user-attachments/assets/12af9220-cae6-4316-8d28-d63815b14051

![exclusive offer](https://github.com/user-attachments/assets/4903d01d-d451-4ce3-bf89-446efa75dc8f)
![exclusive offer 2](https://github.com/user-attachments/assets/4f990430-93e1-46bc-ba37-d711925eed73)

**Comment by KGupta2601** [comment]
@PayalKumari10 Can I work on this issue ?
Can you please assign me this issue ?

**Comment by PayalKumari10** [comment]
> @soham0005 @PayalKumari10 Can I work on this issue ? Can you please assign me this issue ?
 @KGupta2601 , Thanks for offering to take this on! Before I assign the issue, could you briefly outline how you plan to approach building this? This will help ensure everything aligns with the project requirements.

**Comment by KGupta2601** [comment]
Since we want to create a carousel we will be using flexbox for creating responsive carousel. also we will fetch the API key from MI Store.

**Comment by KGupta2601** [comment]
@PayalKumari10 Thank you for assigning me this issue. I am working on it .

**Comment by PayalKumari10** [comment]
> @PayalKumari10 Thank you for assigning me this issue. I am working on it .

Hello @KGupta2601  I wanted to see if you had any updates in this issue ?

**Comment by KGupta2601** [comment]
Hello @PayalKumari10 actually I was suffering from fever since last 3-4 days ...
so will it be okay if I update in a day or two?

**Comment by PayalKumari10** [comment]
> actually I was suffering from fever since last 3-4 days ...
> so will it be okay if I update in a day or two?

okay fine @KGupta2601 Well, you can do it in 2 days.

**Comment by PRathod27** [comment]
@KGupta2601 Any updates?

**Comment by PRathod27** [comment]
Ok @KGupta2601. We will review it.
Thank you for conveying.
