### ISSUE TITLE
Added the security

### ISSUE THREAD

**Issue by Dipanita45** [soham0005/ElectroKart#292]
Please assign me the issue
@soham0005

**Comment by PRathod27** [comment]
@Dipanita45 Do demonstrate the issue properly. Then only we can assign someone an issue.

**Comment by Dipanita45** [comment]
I will add necessary security to protect the website against the harms

**Comment by PRathod27** [comment]
Can you please demonstrate how will you implement this feature?

**Comment by Dipanita45** [comment]
I will add a security file in readmed

**Comment by Dipanita45** [comment]
Please assign me the issue

**Comment by PRathod27** [comment]
@Dipanita45 You can start working on the issue.
