### ISSUE TITLE
Update the Footer of the Website with Mobile Responsive 

### ISSUE THREAD

**Issue by rajatsinghal02** [soham0005/ElectroKart#30]
I want to update the footer of the website with desktop and mobile version both.

![Screenshot_20241004_005810.jpg](https://github.com/user-attachments/assets/b55eb6b2-5dcc-408b-846e-a3d31c80433b)

@PayalKumari10 @soham0005 Please assign this issue to me..

**Comment by PayalKumari10** [comment]
Hello @rajatsinghal02 ,

Thank you for taking on the task of updating the footer to make it mobile responsive! Before you begin, could you please outline the steps you plan to take to tackle this issue? This will help ensure we're on the same page and allow me to provide any additional feedback if necessary.

Looking forward to your plan! 😊

**Comment by PayalKumari10** [comment]
Hi @rajatsinghal02 

Thank you for your efforts in updating the footer! I appreciate your work on adding the contact info, company details, layout adjustments for both desktop and mobile, and the social media icons.

However, I noticed that another contributor is also working on a similar footer update. To avoid duplication of work, I’ll be closing this issue for now. Your contributions are valuable, and I encourage you to explore other open issues where you can apply your skills.

Thank you again, and I look forward to your future contributions!

Best regards,
Payal Kumari
