### ISSUE TITLE
Bug: Videos Not Playing in Videothumbnels on the Videos section

### ISSUE THREAD

**Issue by Sumanbhadra** [soham0005/ElectroKart#32]
Description:
The video section of the website, specifically the Videothumbnels feature, is not functioning as intended. While the video thumbnails are visible, the videos themselves are not loading or playing. This issue is impacting the user experience and potentially hindering product demonstrations and customer engagement.

Expected Behavior:
When a user clicks on a video thumbnail, the corresponding video should begin playing seamlessly within the video thumbnail.

Potential Causes:
Incorrect video file format or encoding or videos are not there.

Priority: High

@soham0005 Please assign this task to me for GSSOC extn.

**Comment by soham0005** [comment]
@Sumanbhadra do create another branch and work on that branch to maintain consistency.

**Comment by soham0005** [comment]
@Sumanbhadra right now, we do not have enough video links to have rendering, so it's in our todo

**Comment by Sumanbhadra** [comment]
For now, I can add some YouTube videos of the products.
