### ISSUE TITLE
Feature Request: Add FAQ Page to Website

### ISSUE THREAD

**Issue by BhaktiMore18** [soham0005/ElectroKart#33]
I would like to enhance the website by adding a Frequently Asked Questions (FAQ) page. This page will provide users with answers to common queries, improving user experience and reducing repetitive questions. The FAQ section should be easy to navigate and visually consistent with the overall website design. Please assign this issue to me so I can start working on it.

**Comment by soham0005** [comment]
@BhaktiMore18 do add atleast 6-7 FAQs, reach out to us if feel stuck or having any doubt.

**Comment by BhaktiMore18** [comment]
Sure!!

**Comment by BhaktiMore18** [comment]
https://github.com/user-attachments/assets/b581b393-9c9e-4c72-a046-13b507fe7f7b

I’ve finished the FAQ page, which covers some common questions and useful info for users. I’d appreciate it if you could check it out and share any feedback or suggestions for improvement.

**Comment by soham0005** [comment]
@BhaktiMore18 great work!!
Just a quick update, the Navbar have been changed so you need to pull the latest updates first then check if there are any conflicts with your current code and the code you pulled
Also some changes to be made are:
![image](https://github.com/user-attachments/assets/c46ce4aa-7c71-430c-9738-88a0e07e7cc8)

- Keep the background color solid and simple and also change the color theme of question box
- Replace Support with FAQs

Do reach out if you feel stuck or having any doubt

**Comment by soham0005** [comment]
@BhaktiMore18 any updates?

**Comment by BhaktiMore18** [comment]
https://github.com/user-attachments/assets/4960e383-efee-48fc-884a-12e3f6cc7d03

Yes, I’ve made the changes you suggested:
- The FAQ background is now solid and simple.
- The color theme of the question box has been updated.
- “Support” has been replaced with “FAQs”
If you have any feedback or need further adjustments, just let me know!

**Comment by soham0005** [comment]
@BhaktiMore18 Great work!
Do pull the latest changes and make your PR
