### ISSUE TITLE
Contact us section 

### ISSUE THREAD

**Issue by Kartikey2011yadav** [soham0005/ElectroKart#34]
the current contact us/ stay in touch section is quite minimalist
![241004_17h56m38s_screenshot](https://github.com/user-attachments/assets/0f0bc282-d2c6-4d71-b806-1e52a26ff0a4)
i think it should be much much more attractive and futuristic.
 i request you to assign this task to me.

**Comment by soham0005** [comment]
@Kartikey2011yadav someone is working on this issue, thank you for the participation. 
Please do check for other issues
