### ISSUE TITLE
Add earbuds section using real mi site data

### ISSUE THREAD

**Issue by mannar-1** [soham0005/ElectroKart#38]
i want to use data of mi site here and display the result according

below is posytman curl i have got image,name,price of product . now i will display it . same i will use fetch/axios in our reat
please assign it to me 
curl --location 'https://www.mi.com/in/product-list/audio/tws-earphone/' \
--header 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7' \
--header 'accept-language: en-US,en;q=0.9,en-IN;q=0.8' \
--header 'cache-control: max-age=0' \
--header 'cookie: _ot_session_id=1728046900429; _ot_instance_id=ctmkkzhe6zh9x862iv1e0ogcrab75bga; _ot_utm_channel=; _ot_utm_content=; _ot_utm_term=; _ot_utm_type=; moeEnable=true; _ot_item_list_name=product-list_audio_tws-earphone.list; _ot_item_list_id=product-list_audio_tws-earphone.6; _ot_last_source=; _ot_view_tip=16.28.6.0.16931.84400851; _ot_ref_tip=; _ot_referrer_path=https://www.mi.com/in/errors/404; _ot_prev_uri_path=https://www.mi.com/in/errors/404; _ot_curr_uri_path=https://www.mi.com/in/product-list/audio/tws-earphone/; _ot_ref_b=28; _ot_last_time=1728048111325; xm_geo=IN; xm_user_bucket=8; _gid=GA1.2.1000309971.1728046901; xmuuid=XMGUEST-BC6011A5-4467-DE5A-1890-95D2A90F8C0B; _gcl_au=1.1.712355150.1728046901; _fbp=fb.1.1728047341505.80774778502185006; lastsource=localhost; mstuid=1728047342204_97; mstz=||1099030861.2||http%3A%2F%2Flocalhost%3A3000%2F|; xm_vistor=1728047342204_97_1728047342205-1728047346129; utmMedium=organic; moe_uuid=b8c2e475-247c-4282-bf66-49070047bc4f; USER_DATA=%7B%22attributes%22%3A%5B%5D%2C%22subscribedToOldSdk%22%3Afalse%2C%22deviceUuid%22%3A%22b8c2e475-247c-4282-bf66-49070047bc4f%22%2C%22deviceAdded%22%3Atrue%7D; SOFT_ASK_STATUS=%7B%22actualValue%22%3A%22not%20shown%22%2C%22MOE_DATA_TYPE%22%3A%22string%22%7D; OPT_IN_SHOWN_TIME=1728047602560; HARD_ASK_STATUS=%7B%22actualValue%22%3A%22dismissed%22%2C%22MOE_DATA_TYPE%22%3A%22string%22%7D; _gat=1; _ga_JV35QQSH38=GS1.2.1728047867.1.1.1728048106.60.0.0; RT="z=1&dm=www.mi.com&si=d7bbfcb3-d138-4889-96bc-7658c9c036e0&ss=m1uqi6bb&sl=3&tt=4da&bcn=%2F%2F684dd328.akstat.io%2F&obo=2&ld=py9l&r=4uc2v89m&ul=q0tx&hd=q18p"; _ga=GA1.1.315100353.1728046901; SESSION=%7B%22sessionKey%22%3A%22b1cc651e-7fd4-420a-922d-0ca648761d9a%22%2C%22sessionStartTime%22%3A%222024-10-04T13%3A13%3A19.426Z%22%2C%22sessionMaxTime%22%3A1800%2C%22customIdentifiersToTrack%22%3A%5B%5D%2C%22sessionExpiryTime%22%3A1728049913585%2C%22numberOfSessions%22%3A1%7D; _ga_YYVZDLF0XE=GS1.1.1728047522.1.1.1728048129.15.0.0; xm_user_bucket=8; xm_user_bucket=8' \
--header 'priority: u=0, i' \
--header 'referer: https://www.mi.com/in/errors/404' \
--header 'sec-ch-ua: "Microsoft Edge";v="129", "Not=A?Brand";v="8", "Chromium";v="129"' \
--header 'sec-ch-ua-mobile: ?1' \
--header 'sec-ch-ua-platform: "Android"' \
--header 'sec-fetch-dest: empty' \
--header 'sec-fetch-mode: navigate' \
--header 'sec-fetch-site: same-origin' \
--header 'upgrade-insecure-requests: 1' \
--header 'user-agent: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Mobile Safari/537.36 Edg/129.0.0.0'

**Comment by soham0005** [comment]
@mannar-1 good idea, let us finish the basic structure and workflow then we can implement your idea
