### ISSUE TITLE
Bad Responsiveness

### ISSUE THREAD

**Issue by rishabhrawat05** [soham0005/ElectroKart#4]
Hi! @soham0005 
The responsiveness of the app needs some work
Here is the attached screenshot of how it looks now

![IMG-20241001-WA0007](https://github.com/user-attachments/assets/725e28ee-3bef-4721-afe7-8da8583b2c94)

Can you please assign this issue to me

**Comment by soham0005** [comment]
Hello @rishabhrawat05! Do reach out to us if you have any doubts regarding responsiveness!

**Comment by soham0005** [comment]
@rishabhrawat05 any updates?

**Comment by rishabhrawat05** [comment]
> @rishabhrawat05 any updates?

Will start working on it from today

**Comment by rishabhrawat05** [comment]
Here's a small update @soham0005 
I have fixed the alignment of all elements for desktop version including removing white spaces due to overflow.

**Comment by soham0005** [comment]
@rishabhrawat05 great work! let me know once you are done with work, we can review it to proceed for the PR
