### ISSUE TITLE
Bug: Frontend Routing

### ISSUE THREAD

**Issue by soham0005** [soham0005/ElectroKart#40]
- Routing not working properly

**Comment by PRathod27** [comment]
@Durga-prasad-1 I'm already working on it.

**Comment by Durga-prasad-1** [comment]
if you require any help ,then let me know

**Comment by Shirisha-16** [comment]
@soham0005 can u say in detail regarding routing . The issue you mentioned is for overall website or in some particular pages . 
I have found an issue which i want to mention . If that issue was completed . I will leave that part .

**Comment by soham0005** [comment]
Hello @Shirisha-16, thank you for the concern, tis routing issue is being handled by one of the colloborator and this bug is for entire routing of frontend

**Comment by NK-Works** [comment]
@Shirisha-16 I can work on this issue 
please assign me
