### ISSUE TITLE
Implement Login and SignUp API with JWT Authentication and Validation

### ISSUE THREAD

**Issue by manu-hn** [soham0005/ElectroKart#42]
Hey @soham0005 
The project currently lacks an API for the Login and SignUp fields. I'd like to implement these features within the controller using the following:

1. JWT authentication for secure login and session management.
2. Validation using Joi to ensure proper data handling and security for user inputs.

Please assign this issue to me, and kindly add the gssoc-extd and hacktoberfest labels along with any other suitable labels. Let me know if you have any additional requirements or suggestions!

**Comment by soham0005** [comment]
Hello @manu-hn , this issue already exists, do consider raising another issue or contributing to other issues. happy coding!
