### ISSUE TITLE
Functionality: Implement JWT Functionality

### ISSUE THREAD

**Issue by AkankshaSinghK** [soham0005/ElectroKart#43]
@soham0005 
Develop and implement a seamless login and registration system, integrating both frontend and backend functionalities, with secure authentication using JSON Web Tokens (JWT). This will ensure secure user sessions, enabling users to log in and register efficiently while maintaining data integrity and security across the application.

On clicking on register nothing is opening in the browser.

![image](https://github.com/user-attachments/assets/1bb7e172-1081-492f-a7ae-e22c9bc6ced7)

Kindly assign this issue to me to add login and register functionality and add gssoc-extd and hactoberfest tags and level it.

**Comment by PRathod27** [comment]
@AkankshaSinghK Thank for raising the issue, but this someone is already on it..
More issues will be there. 
Till Then, Stay Tuned.

**Comment by soham0005** [comment]
@AkankshaSinghK You can implement JWT functionality
Points to be remembered while implementing:
- Do pull the changes first and create another branch for jwt
- return appropriate response along with status code and message
- Do attach the screenshot of Postman of the tested API

**Comment by AkankshaSinghK** [comment]
@soham0005 
Can you please tell the steps for pull the changes
After forking the repo should i pull changes

**Comment by PRathod27** [comment]
@AkankshaSinghK There is a contributor.md file which guides on you should set up and start working on the project. Please go through it and even if then you face issues then reach out to us.

**Comment by AkankshaSinghK** [comment]
@PRathod27  Before forking i need to pull first.
can you please tell me.

**Comment by PRathod27** [comment]
> @PRathod27 Before forking i need to pull first. can you please tell me.

Have you before forked this repo

**Comment by AkankshaSinghK** [comment]
@PRathod27 No

**Comment by soham0005** [comment]
@AkankshaSinghK can you connect on discord, I'll provide detailed steps to setup the project

**Comment by PRathod27** [comment]
> @PRathod27 No

1. First fork it.
2. Create a new branch so you can work on it.

**Comment by AkankshaSinghK** [comment]
@soham0005 yes we can connect

**Comment by soham0005** [comment]
@AkankshaSinghK soham.215

**Comment by AkankshaSinghK** [comment]
@soham0005 
 akankshasingh_

**Comment by soham0005** [comment]
Will connect in afternoon

**Comment by lakshay2425** [comment]
@AkankshaSinghK Would you like to collaborate for this feature? I have integrated this functionality various time.

**Comment by ekayZ7875** [comment]
Hello @AkankshaSinghK i would like to work upon this issue.Please assign it to me.
