### ISSUE TITLE
Add swipe feature and minor design changes to banner on home page

### ISSUE THREAD

**Issue by rahulvarma2005** [soham0005/ElectroKart#48]
I want to add a swipe feature to the banner on home page. This would enable the user to scroll through the slides with a swipe. This is being done by keeping mobile users in mind. Swiping is better than clicking the arrow to get to the next slide. 
Note: This is just an additional feature. The default movement by clicking on arrow would still be present.

-> Change the transition type because the existing one is flashy to the eyes.
-> Change the design of the indicators to match the UI

**Comment by rahulvarma2005** [comment]
@soham0005 Could please assign this issue to me under the label of GSSoC-exd and Hacktoberfest

**Comment by soham0005** [comment]
@rahulvarma2005 great idea, can you implement swipe functionality without removing the arrows
swipe feature can be useful for mobile version whereas users using through laptop or desktops can use the arrow functionality

**Comment by rahulvarma2005** [comment]
Done! I will do it.

**Comment by rahulvarma2005** [comment]
@soham0005 I have raised a pull request for this issue.

**Comment by soham0005** [comment]
@rahulvarma2005 great work!
Thank you for your contribution to our project! 🎉 Feel free to contribute further and help solve any open issues. We'd love to see your continued involvement!
Happy Coding !
