### ISSUE TITLE
Feature: Add a back to top button

### ISSUE THREAD

**Issue by Abankita** [soham0005/ElectroKart#49]
@soham0005 The website should have a back to top button for a better user experience. If you like my proposal and assign me, I can start working on it. 
Thank you!

**Comment by Abankita** [comment]
@soham0005 please assign this assign this issue to me.

**Comment by soham0005** [comment]
@Abankita please fork the repo, create another branch and then start working.
Also attach the screenshot once done.
Feel free to contact incase of having any doubts

**Comment by Abankita** [comment]
@soham0005 I'm sorry I'm not able to fix this one due to a lot of technical errors. Thanks for giving this chance and looking forward to contribute in some other way. Apologies again!
