### ISSUE TITLE
small Footer updates along with icons

### ISSUE THREAD

**Issue by vedhcet-07** [soham0005/ElectroKart#50]
Sir i saw that footer is not properly designed . maybe you have some one else to design , but i have 2 bugs apart from whole footer . These are small but at the end it counts

![image](https://github.com/user-attachments/assets/dc0d1bbb-e952-46b0-974a-6324e853aebd)

The twitter logo and the copyright thing . plus adding proper links and mail . 

i have worked on this earlier . By the time you are reading this i have already started working on it .So if you just assign this to me .. i will immediately give a pull request 

this is my initial stage of open source sir , so more to learn . 

Thank you

**Comment by soham0005** [comment]
@vedhcet-07 before proceeding, please do attach the necessary screenshot of how footer will look like, me and my team will review it once then we can assign it to you

**Comment by vedhcet-07** [comment]
> @vedhcet-07 before proceeding, please do attach the necessary screenshot of how footer will look like, me and my team will review it once then we can assign it to you

sir i am unable to test it on my local machine but i will give the updated thing pls check if possible via PR

**Comment by soham0005** [comment]
@vedhcet-07 is there any error you're facing while testing on local machine
