### ISSUE TITLE
Add fevicon and change to website name

### ISSUE THREAD

**Issue by YasirKhan231** [soham0005/ElectroKart#54]
Change the fevicon and change the react app -  Electrokart  .  

![image](https://github.com/user-attachments/assets/ddb8b529-c084-4253-8b30-a611197a60a1)

**Comment by khushiiagrawal** [comment]
can you assign me this under GSSOC-ext and hectoferfest2024

**Comment by soham0005** [comment]
hello @YasirKhan231 @khushiiagrawal , the issue already exists please do consider raising another issue or contributing to another isses. Happy Coding!
