### ISSUE TITLE
Click on logo to go home page

### ISSUE THREAD

**Issue by YasirKhan231** [soham0005/ElectroKart#55]
Their is no click option are present on the logo . When we hover on the logo then cursor pointer is not showing .

![image](https://github.com/user-attachments/assets/a88c44ee-5b4a-49e3-868a-a8f9e57fafa5)

after changing when we click on the logo then we go to the home page

**Comment by lakshay2425** [comment]
@soham0005 I would like to work on this feature. Please assign me.

**Comment by YasirKhan231** [comment]
@soham0005  give me the task i also add the good css to the logo and do work fast

**Comment by PRathod27** [comment]
@lakshay2425 and @YasirKhan231 This changes are to be done by other contributor. Do, find a new issue.
