### ISSUE TITLE
Feature : Scroll to Top button 

### ISSUE THREAD

**Issue by archanasingh11** [soham0005/ElectroKart#56]
**Description:**

The ElectroKart website currently lacks a **"Scroll to Top"** button, which is a key feature for enhancing user experience, especially on pages with extensive content. Without this button, users have to manually scroll back to the top of the page, which can be inconvenient and time-consuming.

Implementing a **"Scroll to Top"** button would:
- Improve the website's accessibility and usability.
- Provide a smoother navigation experience, particularly on long articles or blog posts.
- Align the user interface with modern design practices.

I recommend adding a floating "Scroll to Top" button that becomes visible as users scroll down the page.

Please @soham0005  assign me this with labels "GSSOC-Ext", "hacktoberfest-accepted" and "level2".

**Comment by samyak-aditya** [comment]
Hey @archanasingh11 please assign me this issue

**Comment by soham0005** [comment]
@archanasingh11 you can start working on it

**Comment by soham0005** [comment]
Hello @archanasingh11, this issue already exists do consider to contributing to other issues
