### ISSUE TITLE
Addition of All Contributors Photos in Readme | Readme Updation

### ISSUE THREAD

**Issue by shubhagarwal1** [soham0005/ElectroKart#57]
We can add a file in workflows to add the contributors automatically to readme which basically enhaces the repo visibility
Hey @soham0005  please assign this task to me with level tag

**Comment by soham0005** [comment]
@shubhagarwal1 will this file get updated automatically?

**Comment by shubhagarwal1** [comment]
> @shubhagarwal1 will this file get updated automatically?

yes

**Comment by soham0005** [comment]
@shubhagarwal1 you can start working on it
