### ISSUE TITLE
integrate Google-Oauth in signup page 

### ISSUE THREAD

**Issue by Shubhamkumar1122001** [soham0005/ElectroKart#58]
@soham0005 please assign me under gssoc-exd24 
![image](https://github.com/user-attachments/assets/122ea353-d561-4ac0-8ace-493359916c88)

**Comment by geetanjalidubey9** [comment]
i would really like to work on this feature

**Comment by soham0005** [comment]
@Shubhamkumar1122001 @lakshay2425 @geetanjalidubey9 , thank you for the interest. Indeed this feature is required to be implemented.
Once the basic Structure of backend and JWT is implemented, this issue will be get assigned and our team will contact you for the same

**Comment by soham0005** [comment]
Hello @Shubhamkumar1122001 @geetanjalidubey9 @lakshay2425, this issue need to be implemented, let me know who wants to work on this

**Comment by geetanjalidubey9** [comment]
I am ready to work on it

**Comment by geetanjalidubey9** [comment]
Pls assign this to me

**Comment by soham0005** [comment]
@geetanjalidubey9 you can start working on it, make sure you attach the screenshot of it and also elaborate what you are going to implement

**Comment by Shubhamkumar1122001** [comment]
@soham0005  I integrate almost half work... I need 1 day to complete it

**Comment by Shubhamkumar1122001** [comment]
Please assign to me dear @soham0005 ... I searched the issue...

**Comment by shrutilad20** [comment]
I am ready to work on it asign to me
