### ISSUE TITLE
Update Readme.md

### ISSUE THREAD

**Issue by rajatsinghal02** [soham0005/ElectroKart#61]
@soham0005 I want to update the Readme.md file according to the project.

Please assign this issue to me.

**Comment by soham0005** [comment]
@rajatsinghal02 do share the contents for readme

**Comment by soham0005** [comment]
@rajatsinghal02 Some additional Points to be added:-

- Icons for Tech Stack
- Mention Code of Conduct Readme Link

Do reach out if you have any doubts. Happy Coding!

**Comment by soham0005** [comment]
@rajatsinghal02 i did not get your doubt, is it counted in leaderboard of not?
There are some PRs that have not been counted yet, I have raised issue for that, it may get updated soon dw

**Comment by soham0005** [comment]
@rajatsinghal02 okay great, as PR have labels so it is counted
