### ISSUE TITLE
fix the register page ui 

### ISSUE THREAD

**Issue by AyushSharma72** [soham0005/ElectroKart#62]
hey @soham0005 the register page ui is not looking appropriate according to the screen size

![image](https://github.com/user-attachments/assets/c5e25a9a-8950-4af2-9703-b2659b1ab6e7)

i will make the register page appropriate for all device widths 

please assign me the issue  and mark this issue atleast level2

**Comment by soham0005** [comment]
@AyushSharma72 hello, this issue is already in progress, do consider raising other issue or contributing to other issues.
Happy Coding!
