### ISSUE TITLE
Add License File to Repository

### ISSUE THREAD

**Issue by rahulgithub-web** [soham0005/ElectroKart#63]
## Task
1. Choose an appropriate open-source license.
2. Add the `LICENSE` file to the root of the repository.
3. Update `README.md` to include a reference to the license.

#
@soham0005 Please assign this task to me with all the required labels attached to it.

**Comment by soham0005** [comment]
Hello @rahulgithub-web , this issue is already being raised, do consider raising another issue or contributing to other issue.
Happy Coding!
