### ISSUE TITLE
Navbar Update

### ISSUE THREAD

**Issue by rajatsinghal02** [soham0005/ElectroKart#67]
I want to update the navbar of the website with space and styling

The navbar have so much space in top and bottom which looks poor
I want to add hover effects on the items of navbar
![Screenshot 2024-10-06 152026](https://github.com/user-attachments/assets/1297254a-a1f6-4620-9f0c-d803ed4f7398)

@soham0005 Please assign this issue to me.

**Comment by soham0005** [comment]
@rajatsinghal02 This issue is already being assigned to other contributor!
