### ISSUE TITLE
Fixing search UI

### ISSUE THREAD

**Issue by sakshii00** [soham0005/ElectroKart#71]
When search is opened, it comes over the other available buttons as shown in image. I would like to fix this.

![image](https://github.com/user-attachments/assets/44002672-005a-481c-8ccc-2330ab2c223a)

**Comment by PayalKumari10** [comment]
The search UI has been removed as required. Closing this issue.

> When search is opened, it comes over the other available buttons as shown in image. I would like to fix this.
> 
> ![image](https://private-user-images.githubusercontent.com/92578876/373971206-44002672-005a-481c-8ccc-2330ab2c223a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzMTUzODQsIm5iZiI6MTcyODMxNTA4NCwicGF0aCI6Ii85MjU3ODg3Ni8zNzM5NzEyMDYtNDQwMDI2NzItMDA1YS00ODFjLThjY2MtMjMzMGFiMmMyMjNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDE1MzEyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxNTI0YjlhMDgyMmE4ZjRjZmFhOTI5N2RjNTBlMzI4OWJmMWU1NjlmNDhiNjY0NjljOWNhYmRhNTI3NzRlYjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._ECzbyxso8mns93YLcI2OCD7c8qm3q13jBt6hTJ-dBw)

The search UI has been removed as required. Closing this issue.

**Comment by sakshii00** [comment]
The search is still there in the vercel deployed app- @PayalKumari10

**Comment by soham0005** [comment]
@sakshii00 the updated version is to be deployed manually which will be done today and the search icon will removed

**Comment by sakshii00** [comment]
Alright
