### ISSUE TITLE
[Feature]: Adding a Support Page For Support and Feedback Mechanism

### ISSUE THREAD

**Issue by yeshwanth-ds** [soham0005/ElectroKart#72]
# User Support and Feedback Mechanism 

## Problem Statement
Currently, the ElectroKart platform lacks a dedicated support page for users to submit inquiries and feedback. This gap prevents users from easily communicating their questions or issues, which can lead to frustration and dissatisfaction with the platform.

## Why We Need a Support Page
Having a support page with contact forms is essential for enhancing user experience. It allows users to:
- Communicate their concerns or inquiries effectively.
- Receive timely responses from the support team.
- Feel valued and heard, which can increase overall customer satisfaction.

## Benefits
- **Improved User Satisfaction**: By providing a straightforward way for users to reach out, we enhance their experience and increase the likelihood of repeat business.
- **Efficient Inquiry Management**: Implementing multi-department routing allows for more efficient handling of inquiries by directing them to the appropriate team.
- **Enhanced Communication**: Automated confirmation and follow-up emails keep users informed about the status of their inquiries, improving transparency.

## Technical Tasks
To implement the contact forms for general inquiries, the following technologies will be utilized:
- **HTML**: For structuring the contact form.
- **CSS**: For styling the form to ensure it is visually appealing and user-friendly.
- **JavaScript**: For dynamic form fields and handling form submission, including validation and user feedback.

## Key Features to Implement
1. **Dynamic Form Fields**: Allow users to add additional information dynamically (e.g., additional comments or specific product details).
2. **Multi-Department Routing**: Implement routing based on the subject or category selected by the user, directing inquiries to specific departments (e.g., Sales, Technical Support).

## Task Assignment
This task is open for contribution under the following initiatives:
- **Hacktoberfest**
- **GSSoC-EXT**

I will be linking this suppot page to the support **anchor.**

![Screenshot 2024-10-06 234913](https://github.com/user-attachments/assets/12953de5-364c-48fc-882a-0d84cb9647b8)

**Comment by soham0005** [comment]
@yeshwanth-ds, thank you for raising the issue, the Support will be replaced by FAQs. Please do consider raising another issue or contributing to other issue. Happy Coding!
