### ISSUE TITLE
Bug : Missing Submit Button for Email Input Field

### ISSUE THREAD

**Issue by Saurabhchaudhary9799** [soham0005/ElectroKart#73]
**Description:**

The email input field in the contact section lacks a visible submit button for users to complete their subscription or signup process. While there is an arrow icon, its functionality and purpose may not be clear to all users. For a better user experience, a clearly labeled Submit button should be added alongside the input field.

**Proposed Solution:**

1. Add a Visible Submit Button:
2. Introduce a standard submit button with a clear label like "Submit" or "Sign Up" next to the email input field to ensure users understand how to complete their email subscription.

**Enhanced Button Design:**

Style the button to be more prominent, using appropriate colors, hover effects, and font size to improve visibility and usability.
Accessibility Improvements:

Ensure that the button is accessible for users with disabilities, such as those using screen readers, by providing appropriate aria-labels and making it keyboard-navigable.

**Screenshot of Current UI**
![Screenshot from 2024-10-07 01-45-07](https://github.com/user-attachments/assets/51ab7a2b-1654-49ec-a367-6d4f6f2bb368)

**Confirmation Feedback:**

After the user submits their email, provide a clear confirmation message (e.g., “You’ve been subscribed!”) to enhance the overall user experience.

**Comment by harshthakkr** [comment]
Can I use the Sonner library for toast message for confirmation feedback?

**Comment by SaanyaGarg5** [comment]
you can assign this task to me

**Comment by soham0005** [comment]
@Saurabhchaudhary9799 you can start working on this, add button and once button is clicked, try to implement email functionality that will send email to the registered email
