### ISSUE TITLE
Add Mongoose Data Schema for Phone, Tablet, TV & Smart Appliances, Smart Watch & Audio.

### ISSUE THREAD

**Issue by IkkiOcean** [soham0005/ElectroKart#75]
We need to extend the Mongoose data schema in the Electro-Kart web project to support new product categories: Phone, Tablet, TV & Smart Appliances, Smart Watch & Audio. This will allow the application to store and manage these categories of products, each with its relevant attributes, in the database.

Proposed Changes:

	1.	Phone Schema:
	
	2.	Tablet Schema:
	
	3.	TV & Smart Appliances Schema:
	
	4.	Smart Watch Schema:
	
	6.	Audio Schema:

What I will Do:

	•	Mongoose schema for each product category and structured according to the provided specifications.
	•	All new schemas should be added to the existing MongoDB models.
	•	Document the schemas properly with comments describing the fields and their expected values.

**Comment by soham0005** [comment]
Hello @IkkiOcean, thank you for raising this issue, Indeed it is going to be implemented in the near future, our team will contact for the same
Happy Coding!

**Comment by IkkiOcean** [comment]
Assign me the issue
