### ISSUE TITLE
Login/SignUp Backend error

### ISSUE THREAD

**Issue by eshaalal** [soham0005/ElectroKart#77]
During Registration Error is happening:
![Screenshot 2024-10-07 145704](https://github.com/user-attachments/assets/5c7b54fe-f48e-4386-8256-456bc8136473)

Tasks I would like to work on
1. Implemented user authentication using Node.js and JWT (JSON Web Token).
2. Provided secure login and signup functionality.
3. Token-based authentication for managing user sessions.

**Comment by eshaalal** [comment]
@soham0005 I would like to work on this issue

**Comment by soham0005** [comment]
Hello @eshaalal , the issue raised by issue is already implemented and will get merged today. Please do consider raising another issue or contributing to other issues. Happy Coding!!
