### ISSUE TITLE
Add Switching of dark and light mode button in Navbar

### ISSUE THREAD

**Issue by 2004vivek** [soham0005/ElectroKart#8]
Problem
Navbar is having missing switching of dark mode to light mode and vice versa option .So my suggestion is to add that option and increase the height of the navbar in order to have good ui.

Solution
We can implement this things by using usestate hooks in react which allows us to re-render our component

Please assign me this task!

![image](https://github.com/user-attachments/assets/3c9445dc-8e09-478c-bcff-7ae21324ff6c)

**Comment by Laxmi01345** [comment]
I want to work on this issue . Please assign it to me.

**Comment by soham0005** [comment]
@Laxmi01345 @2004vivek The contributors are already working on this issue, thank you for the participation
