### ISSUE TITLE
[BUG] Issue in Search bar 

### ISSUE THREAD

**Issue by Durga-prasad-1** [soham0005/ElectroKart#80]
**Description**
There is a problem in opening and closing of search bar in desktop, that is the search bar overlaps the register and support button when the search bar is opened 

**Before solving**

https://github.com/user-attachments/assets/1dee14ff-38e4-447b-87dd-8138d09f337a

**After solving**

https://github.com/user-attachments/assets/873d8250-c82c-45a8-afc4-28977418183c

I have figured out the issue, please assign this task to me so that , i can make a pull request
Please @soham0005 assign me this with labels "GSSOC-Ext", "hacktoberfest-accepted".

**Comment by Durga-prasad-1** [comment]
hello sir how can you close the issue , without assigning me . I just
showed the completion of my work, but I didn't made the pull request . and
you didn't even labeled the issue as hacktoberfest or gssoc-ext . i want an
explaination

**Comment by soham0005** [comment]
@Durga-prasad-1, the issue has been resolved by our team and it will be reflected on the hosted website soon
