### ISSUE TITLE
Login and Signup Pages are not that much professional and Good looking for ui/ux

### ISSUE THREAD

**Issue by tarunkumar2005** [soham0005/ElectroKart#82]
![image](https://github.com/user-attachments/assets/754616c6-d48c-427f-b6ce-5cb36d114b3c)

Login and Signup Pages are not that much professional and Good looking for ui/ux. Like the front page login and signup page are very bad looking right now so i want to fix that thing and make them look good and better for ui/ux which makes them user friendly and awersome. 

@soham0005 Assign this to under gssoc 2024 ext and hacktoberfest i will work on this issue.

**Comment by soham0005** [comment]
Hello @tarunkumar2005, this issue is already being fixed by other contributor, please do consider contributing to other issues.
Happy Coding!!
