### ISSUE TITLE
[BUG] Nav Bar Is Too Big

### ISSUE THREAD

**Issue by 4F24L** [soham0005/ElectroKart#83]
![image](https://github.com/user-attachments/assets/5946e697-b8f4-4e2f-950f-70edf2b5aa2e)

### Please add hactoberfest and GSSoC24 tag. You can assign me for this issue.

**Comment by soham0005** [comment]
Hello @4F24L, this issue is already fixed, please do consider contributing to other issues or raising other issues.
Happy Coding!!
