### ISSUE TITLE
Feature : Add Forgot Password functionality on Login Page

### ISSUE THREAD

**Issue by AkankshaSinghK** [soham0005/ElectroKart#85]
@soham0005 
@PRathod27 

Want to add Forgot password functionality so that user can reset their password.

Kindly assign this issue to me and add gssoc-extd and hactoberfest tags and level it.

**Comment by PayalKumari10** [comment]
@AkankshaSinghK , Thank you for contributing to this project! We appreciate your efforts and look forward to seeing your work improve the project.

Happy Coding!
