### ISSUE TITLE
[Feat] ScrollBar Styling

### ISSUE THREAD

**Issue by MishraTanishq619** [soham0005/ElectroKart#86]
## Description
Currently : We have the dafault styles for Scrollbar. We hadn't gave a custom styles to our scrollbar.
Expectation : We can add our custom styles to the scrollbar. So that it can be aligned with our app theme.

I'm a Hacktoberfest'24 contributor
I am willing to work on this issue
Please assign this issue to me.

**Comment by PRathod27** [comment]
@MishraTanishq619 Can you please demonstrate how will you add this feature and attach an example of this type of work if done before.
