### ISSUE TITLE
Horizontal scrollbar in FAQ section

### ISSUE THREAD

**Issue by sakshii00** [soham0005/ElectroKart#88]
![image](https://github.com/user-attachments/assets/47b7d6af-1ddb-4dc0-89a3-e89bbbc13394)
I would like to fix (remove) the horizontal scrollbar that is coming in FAQ section. It is not needed and ruins experience.

**Comment by soham0005** [comment]
@sakshii00 along with this can do something creative related with scrollbar or hide the inner scrollbar?

**Comment by sakshii00** [comment]
I think the horizontal scroll bar can be hidden but I can also implement something if you need. @soham0005 Let me know of your preferences.

**Comment by soham0005** [comment]
@sakshii00 works, also can you style the scrollbar?

**Comment by sakshii00** [comment]
yes sure @soham0005

**Comment by soham0005** [comment]
@sakshii00 any updates?

**Comment by sakshii00** [comment]
@soham0005 I will complete this by today.. i had some problems in my laptop due to which this was delayed, apologies

**Comment by soham0005** [comment]
@soham0005 , no worries, if you have any doubt, do reach out
