### ISSUE TITLE
Feature: Update profile

### ISSUE THREAD

**Issue by AkankshaSinghK** [soham0005/ElectroKart#91]
@soham0005 
User can update their profile to change their existing data.

Kindly assign this to me and add gssoc-extd and hactoberfest tags and level it.

**Comment by soham0005** [comment]
@AkankshaSinghK do share what you are going to implement

**Comment by AkankshaSinghK** [comment]
@soham0005 

The data which user inputted while registering is stored in database and if user wants to update any data from that then they can updtae their information by logging in and update profile option.

**Comment by SaanyaGarg5** [comment]
you can assign that task to me under gsssoc-ext and hacktoberfest.. level 3 label
