### ISSUE TITLE
Adding 404 Error page for the website.

### ISSUE THREAD

**Issue by rahulvarma2005** [soham0005/ElectroKart#98]
I would like to add a (Page not found 404) page to the website. This would also have an option to redirect to the home page for the user.

**Comment by rahulvarma2005** [comment]
@soham0005 Could please assign this issue to me under the label of GSSoC-exd and Hacktoberfest

**Comment by soham0005** [comment]
@rahulvarma2005, do make the 404 page interesting and little bit funny image to be added
