### ISSUE TITLE
Change of color on hovering the Readmore word and addition of links to icons 

### ISSUE THREAD

**Issue by Shirisha-16** [soham0005/ElectroKart#99]
i)color of Readmore changes when we hover that line.
![Screenshot 2024-10-08 160714](https://github.com/user-attachments/assets/614573cf-b0f7-4288-8fd5-1dff16b83ba2)
if possible there should be a link to read full article when we hover the Readmore word .
ii)Addition of links to the icons 
![Screenshot 2024-10-08 160731](https://github.com/user-attachments/assets/a013634f-2f16-48a9-bac7-61b6e19985bc)
I want to work on this issues.
@soham0005  please assign me this task with the labels gssoc-ext,hacktoberfest-accepted and level according to issue.

**Comment by soham0005** [comment]
@Shirisha-16, do reach out if you have any doubt.
Happy Coding!

**Comment by Shirisha-16** [comment]
@soham0005 Do i need to keep a general example link or can u share your links of facebook,twitter,instagram. So that i can add
